app = "xhttp-relay-matin"     # ← این نام را به نام اپ خودت تغییر بده

[build]
  builder = "paketobuildpacks/builder:base"   # این خط مهم است

[env]
  PORT = "8080"
  NODE_VERSION = "20"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
